# Generated by Django 3.2.7 on 2021-09-03 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('birth', models.DateField(null=True)),
                ('height', models.SmallIntegerField(null=True)),
                ('weight', models.SmallIntegerField(null=True)),
                ('picture', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('admin', 'admin'), ('free', 'free'), ('premium', 'premium')], max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
