# Generated by Django 3.2.7 on 2021-09-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rest',
            field=models.DurationField(default=0),
        ),
    ]
