# Generated by Django 3.2.7 on 2021-10-01 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0002_auto_20210919_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='repetition',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('deleted', models.BooleanField(default=False)),
                ('sets', models.SmallIntegerField(default=0)),
                ('repetition', models.SmallIntegerField(default=0)),
                ('rest', models.DurationField(default=0)),
                ('weight', models.SmallIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spodaily_api.session')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_session_id', to='spodaily_api.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
