# Generated by Django 3.2.7 on 2021-10-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0002_auto_20211007_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='exercise',
            new_name='exercise_id',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='session',
            new_name='session_id',
        ),
    ]
