# Generated by Django 3.2.7 on 2021-10-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0003_auto_20211007_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
