# Generated by Django 3.2.7 on 2021-10-29 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0005_auto_20211024_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('deleted', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('Suggestion', 'Suggestion'), ('Bug', 'Bug'), ('Autre', 'Autre')], max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
