# Generated by Django 3.2.7 on 2021-10-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0007_auto_20211030_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_program',
            field=models.BooleanField(default=False),
        ),
    ]
