# Generated by Django 3.2.7 on 2021-10-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0008_session_is_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
