# Generated by Django 3.2.9 on 2021-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0009_session_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='recurrence',
            field=models.PositiveSmallIntegerField(default=7, max_length=500),
        ),
    ]
