# Generated by Django 3.2.9 on 2021-11-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0010_session_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='recurrence',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
