# Generated by Django 3.2.9 on 2021-11-12 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0011_alter_session_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(blank=True, max_length=2, null=True)),
                ('nova', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eco', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ean', models.PositiveBigIntegerField(blank=True, null=True)),
                ('kcal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('proteine', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('glucide', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lipide', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fibre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('deleted', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('is_done', models.BooleanField(default=False)),
                ('recurrence', models.PositiveSmallIntegerField()),
                ('name', models.CharField(choices=[('Petit déjeuner', 'Petit déjeuner'), ('Déjeuner', 'Déjeuner'), ('Goûté', 'Goûté'), ('Diner', 'Diner'), ('Collation', 'Collation')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealXFood',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('deleted', models.BooleanField(default=False)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='spodaily_api.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='spodaily_api.meal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
