# Generated by Django 3.2.9 on 2021-11-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0012_food_meal_mealxfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_email',
            field=models.BooleanField(default=True),
        ),
    ]
