# Generated by Django 3.2.9 on 2021-11-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0013_user_accept_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='rest',
            field=models.DurationField(default='0:00:00'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
