# Generated by Django 3.2.9 on 2021-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0014_auto_20211114_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
