# Generated by Django 3.2.9 on 2021-11-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0017_auto_20211121_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
