# Generated by Django 3.2.9 on 2021-11-29 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0018_auto_20211121_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('deleted', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='spodaily_api.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
