# Generated by Django 3.2.9 on 2021-11-29 19:03

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0019_fitnessgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessgoal',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
