# Generated by Django 3.2.9 on 2021-11-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spodaily_api', '0020_fitnessgoal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessgoal',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
